"use client";

import { useState, useEffect, useRef } from "react";
import { useRouter, useSearchParams, usePathname } from "next/navigation";
import Link from "next/link";
import Image from "next/image";
import { ArrowLeft, Plus, Trash2, Music, Edit2, Save, X, Upload, Users, Lock, Unlock } from "lucide-react";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import { ScrollArea } from "@/components/ui/scroll-area";
import { useToast } from "@/components/ui/use-toast";
import { AddTracksSection } from "@/components/add-tracks-section";
import { ImageUploadCrop } from "@/components/image-upload-crop";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import type { Playlist, PlaylistTrack, PlaylistPermission } from "@/lib/playlist";
import type { LastfmTrack } from "@/lib/lastfm";

type PlaylistDetailClientProps = {
  initialPlaylist: Playlist;
  username: string;
};

export function PlaylistDetailClient({ initialPlaylist, username }: PlaylistDetailClientProps) {
  const [playlist, setPlaylist] = useState<Playlist>(initialPlaylist);
  const [loading, setLoading] = useState(false);
  const [isEditing, setIsEditing] = useState(false);
  const [editName, setEditName] = useState(playlist.name);
  const [editDescription, setEditDescription] = useState(playlist.description || "");
  const [isSaving, setIsSaving] = useState(false);
  const { toast } = useToast();
  const router = useRouter();
  const pathname = usePathname();
  const searchParams = useSearchParams();
  const isNewPlaylist = searchParams.get("new") === "true";
  const hasBeenModified = useRef(false);
  const initialTrackCount = useRef(playlist.tracks.length);
  const initialName = useRef(playlist.name);
  const previousPathname = useRef(pathname);
  
  // Check if playlist name is auto-generated (playlist1, playlist2, etc.)
  const isAutoGeneratedName = /^playlist\d+$/i.test(playlist.name);

  const handleRemoveTrack = async (url: string) => {
    try {
      const res = await fetch(`/api/playlists/${playlist._id}/tracks?url=${encodeURIComponent(url)}`, {
        method: "DELETE",
      });

      if (res.ok) {
        setPlaylist({
          ...playlist,
          tracks: playlist.tracks.filter((t) => t.url !== url),
        });
        toast({ title: "Removed from playlist" });
        router.refresh();
      }
    } catch (error) {
      toast({ title: "Failed to remove track", variant: "destructive" });
    }
  };

  // Get the best available image (consistent with AddTracksSection)
  const getBestImage = (images?: Array<{ size: string; "#text": string }>) => {
    if (!images || images.length === 0) return undefined;
    const img = images.find((i) => i.size === "extralarge")?.["#text"] ||
               images.find((i) => i.size === "large")?.["#text"] ||
               images.find((i) => i.size === "medium")?.["#text"] ||
               images.find((i) => i.size === "small")?.["#text"] ||
               images[0]?.["#text"];
    return img && img.trim() !== "" ? img : undefined;
  };

  const handleAddTrack = async (track: LastfmTrack) => {
    try {
      const newTrack = {
        name: track.name,
        artist: track.artist["#text"],
        album: track.album?.["#text"],
        image: getBestImage(track.image),
        url: track.url || "#",
      };

      const res = await fetch(`/api/playlists/${playlist._id}/tracks`, {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify(newTrack),
      });

      if (res.ok) {
        const addedTrack: PlaylistTrack = {
          ...newTrack,
          addedAt: new Date(),
        };
        
        // Avoid duplicates
        if (!playlist.tracks.some(t => t.url === newTrack.url)) {
          setPlaylist({
            ...playlist,
            tracks: [addedTrack, ...playlist.tracks],
          });
          hasBeenModified.current = true; // Mark as modified
        }
        
        toast({ title: "Added to playlist" });
        router.refresh();
      } else {
        toast({ title: "Failed to add track", variant: "destructive" });
      }
    } catch (error) {
      toast({ title: "Failed to add track", variant: "destructive" });
    }
  };

  // Detect pathname changes (user navigating away)
  useEffect(() => {
    if (!isNewPlaylist) return;
    
    if (previousPathname.current !== pathname && previousPathname.current === `/playlists/${playlist._id}`) {
      // User navigated away from this playlist page
      // Check if playlist is still empty and unmodified, then delete it
      // Don't delete if user is currently editing or has unsaved changes
      const hasUnsavedChanges = isEditing || editName !== initialName.current || editDescription !== (playlist.description || "");
      
      if (
        !hasUnsavedChanges &&
        playlist.tracks.length === 0 &&
        !hasBeenModified.current &&
        isAutoGeneratedName &&
        playlist.name === initialName.current
      ) {
        fetch(`/api/playlists/${playlist._id}`, {
          method: "DELETE",
        }).catch(() => {
          // Ignore errors during cleanup
        });
      }
    }
    previousPathname.current = pathname;
  }, [pathname, isNewPlaylist, playlist._id, playlist.tracks.length, playlist.name, playlist.description, isAutoGeneratedName, isEditing, editName, editDescription]);

  // Auto-delete empty new playlists when user leaves without saving
  useEffect(() => {
    if (!isNewPlaylist) return;

    const handleBeforeUnload = () => {
      // Check if playlist is still empty and unmodified
      // Don't delete if user is currently editing or has unsaved changes
      const hasUnsavedChanges = isEditing || editName !== initialName.current || editDescription !== (playlist.description || "");
      
      if (
        !hasUnsavedChanges &&
        playlist.tracks.length === 0 &&
        !hasBeenModified.current &&
        isAutoGeneratedName &&
        playlist.name === initialName.current
      ) {
        // Try to delete, but don't wait for response (page is unloading)
        fetch(`/api/playlists/${playlist._id}`, {
          method: "DELETE",
          keepalive: true,
        }).catch(() => {
          // Ignore errors
        });
      }
    };

    window.addEventListener("beforeunload", handleBeforeUnload);

    return () => {
      window.removeEventListener("beforeunload", handleBeforeUnload);
      // Cleanup on unmount
      // Don't delete if user is currently editing or has unsaved changes
      const hasUnsavedChanges = isEditing || editName !== initialName.current || editDescription !== (playlist.description || "");
      
      if (
        !hasUnsavedChanges &&
        playlist.tracks.length === 0 &&
        !hasBeenModified.current &&
        isAutoGeneratedName &&
        playlist.name === initialName.current
      ) {
        fetch(`/api/playlists/${playlist._id}`, {
          method: "DELETE",
        }).catch(() => {
          // Ignore errors during cleanup
        });
      }
    };
  }, [isNewPlaylist, playlist._id, playlist.tracks.length, playlist.name, playlist.description, isAutoGeneratedName, isEditing, editName, editDescription]);

  return (
    <div className="container mx-auto p-6 max-w-6xl">
      <div className="mb-6">
        <Link href="/playlists">
          <Button variant="ghost" size="sm" className="mb-4">
            <ArrowLeft className="mr-2 h-4 w-4" />
            Back to Playlists
          </Button>
        </Link>
        <div className="flex items-center justify-between">
          <div className="flex-1">
            {isEditing ? (
              <div className="space-y-3">
                <div>
                  <Label htmlFor="edit-name">Playlist Name</Label>
                  <Input
                    id="edit-name"
                    value={editName}
                    onChange={(e) => setEditName(e.target.value)}
                    className="mt-1"
                    maxLength={50}
                  />
                </div>
                <div>
                  <Label htmlFor="edit-description">Description</Label>
                  <Textarea
                    id="edit-description"
                    value={editDescription}
                    onChange={(e) => setEditDescription(e.target.value)}
                    className="mt-1"
                    maxLength={200}
                  />
                </div>
                <div className="flex gap-2">
                  <Button
                    size="sm"
                    onClick={async () => {
                      setIsSaving(true);
                      try {
                        const res = await fetch(`/api/playlists/${playlist._id}`, {
                          method: "PUT",
                          headers: { "Content-Type": "application/json" },
                          body: JSON.stringify({
                            name: editName.trim(),
                            description: editDescription.trim() || undefined,
                          }),
                        });

                        if (res.ok) {
                          setPlaylist({
                            ...playlist,
                            name: editName.trim(),
                            description: editDescription.trim() || undefined,
                          });
                          setIsEditing(false);
                          hasBeenModified.current = true; // Mark as modified
                          initialName.current = editName.trim(); // Update initial name
                          toast({ title: "Playlist updated" });
                          router.refresh();
                        } else {
                          toast({ title: "Failed to update playlist", variant: "destructive" });
                        }
                      } catch (error) {
                        toast({ title: "Failed to update playlist", variant: "destructive" });
                      } finally {
                        setIsSaving(false);
                      }
                    }}
                    disabled={isSaving || !editName.trim()}
                  >
                    <Save className="mr-2 h-4 w-4" />
                    Save
                  </Button>
                  <Button
                    size="sm"
                    variant="outline"
                    onClick={() => {
                      setIsEditing(false);
                      setEditName(playlist.name);
                      setEditDescription(playlist.description || "");
                    }}
                    disabled={isSaving}
                  >
                    <X className="mr-2 h-4 w-4" />
                    Cancel
                  </Button>
                </div>
              </div>
            ) : (
              <>
                <div className="flex items-center gap-2 mb-2">
                  <h1 className="text-3xl font-bold">{playlist.name}</h1>
                  <Button
                    variant="ghost"
                    size="icon"
                    onClick={() => setIsEditing(true)}
                    className="h-8 w-8"
                  >
                    <Edit2 className="h-4 w-4" />
                  </Button>
                </div>
                {playlist.description && (
                  <p className="text-muted-foreground">{playlist.description}</p>
                )}
              </>
            )}
          </div>
        </div>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-5 gap-6">
        {/* Add Tracks Section - Inline */}
        <div className="lg:col-span-2">
          <Card>
            <CardHeader>
              <CardTitle>Add Tracks</CardTitle>
            </CardHeader>
            <CardContent className="p-4">
              <AddTracksSection username={username} onAdd={handleAddTrack} autoLoadRecent={false} />
            </CardContent>
          </Card>
        </div>

        {/* Playlist Tracks */}
        <div className="lg:col-span-3">
          <Card>
            <CardHeader>
              <CardTitle>{playlist.tracks.length} Tracks</CardTitle>
            </CardHeader>
            <CardContent>
              <ScrollArea className="h-[600px] pr-4">
                {playlist.tracks.length > 0 ? (
                  <div className="space-y-3">
                    {playlist.tracks.map((track, i) => (
                      <div key={`${track.url}-${i}`} className="flex items-center gap-3 group">
                        <div className="relative h-12 w-12 flex-shrink-0 overflow-hidden rounded-md bg-gradient-to-br from-primary/20 to-primary/5 shadow-sm">
                          {track.image && track.image.trim() !== "" ? (
                            <Image
                              src={track.image}
                              alt={track.name}
                              fill
                              className="object-cover"
                              sizes="48px"
                              onError={() => {}}
                            />
                          ) : (
                            <div className="flex h-full w-full items-center justify-center">
                              <Music className="h-6 w-6 text-primary/60" />
                            </div>
                          )}
                        </div>
                        <div className="min-w-0 flex-1">
                          <a 
                            href={track.url || "#"} 
                            target="_blank" 
                            rel="noopener noreferrer"
                            className="truncate text-sm font-medium hover:underline block"
                          >
                            {track.name}
                          </a>
                          <p className="truncate text-xs text-muted-foreground">
                            {track.artist}
                          </p>
                          {track.album && (
                            <p className="truncate text-xs text-muted-foreground/70">
                              {track.album}
                            </p>
                          )}
                        </div>
                        <Button
                          variant="ghost"
                          size="icon"
                          className="h-8 w-8 opacity-0 group-hover:opacity-100 transition-opacity"
                          onClick={() => track.url && handleRemoveTrack(track.url)}
                        >
                          <Trash2 className="h-4 w-4 text-destructive" />
                        </Button>
                      </div>
                    ))}
                  </div>
                ) : (
                  <div className="flex flex-col items-center justify-center h-full text-center py-12 text-muted-foreground">
                    <Music className="h-12 w-12 mb-4" />
                    <p className="text-sm">No songs in this playlist yet.</p>
                    <p className="text-xs mt-1">Add tracks using the panel on the left.</p>
                  </div>
                )}
              </ScrollArea>
            </CardContent>
          </Card>
        </div>
      </div>
    </div>
  );
}


